# Generated by Django 5.2.8 on 2025-11-24 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studysession',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='user',
        ),
        migrations.DeleteModel(
            name='PomodoroSession',
        ),
        migrations.DeleteModel(
            name='StudySession',
        ),
    ]
